### ISSUE TITLE
AOT Compilation

### ISSUE THREAD

**Issue by letwork** [DevExpress/golfclub#6]
Hi,

i tried "ng build --prod --aot" where i got following errors:

ERROR in ./src/app/clubs.service.ts
Module build failed: Error: C:/tennis04/playground/dxGolfAot/src/app/clubs.service.ts (9,5): Public property 'reservations$' of exported class has or is using name 'Observable' from external module "C:/tennis04/playground/dxGolfAot/node_modules/rxjs/Observable" but cannot be named.)

I added the missing import statements and then build runs without errors.
( import { Observable } from 'rxjs/Observable'; )

But now i got 8 runtime errors, when i opening the index.html
for example:
main.a16927dc74d55844bad0.bundle.js:640 EXCEPTION: Cannot read property 'replace' of undefined
t.handleError @ main.a16927dc74d55844bad0.bundle.js:640

What's the problem here?

Would be helpful if these sample covers all the angular-cli functionality.

**Comment by dxvladislavvolkov** [comment]
Hello @letwork
At the moment the issue is not reproduced on my side. Try to use our changes and reproduce it again.
