### ISSUE TITLE
angular.json refers to tb.light.green.css which can't be found

### ISSUE THREAD

**Issue by PerryCodes** [DevExpress/golfclub#62]
"styles": [
    "node_modules/devextreme/dist/css/dx.common.css",
    "node_modules/devextreme/dist/css/tb.light.green.css"
]

That second css file is not found.  Should it be?

**Comment by babich-a** [comment]
Hi 
This file is generated by devextreme-cli and should be made when [this](https://github.com/DevExpress/golfclub/blob/master/package.json#L10) command is run (https://github.com/DevExpress/golfclub/blob/master/devextreme.json#L38).

**Comment by PerryCodes** [comment]
![image](https://user-images.githubusercontent.com/2401573/101924761-ab4cc380-3b96-11eb-8d12-6726d135128d.png)

**Comment by PerryCodes** [comment]
Do I need to create another issue for this?  I was surprised to see this 'Closed' before I had an opportunity to respond.

**Comment by PerryCodes** [comment]
![image](https://user-images.githubusercontent.com/2401573/101926163-6fb2f900-3b98-11eb-968a-86e371bffe79.png)

**Comment by PerryCodes** [comment]
Running 'npm run build-theme' manually creates the file.  I don't think that file gets created when following the instructions listed on 'README.md'?

**Comment by babich-a** [comment]
You are right! Only ssr commands includes this command now (e.g. https://github.com/DevExpress/golfclub/blob/master/package.json#L12). I'll include it in the `npm start` command and fix the README.
